---
# tasks file for kubernetes
- name: yum install kubernetes etcd
  yum:  name={{ item }} state=present
  with_items:
    - etcd
    - kubernetes

- name: remove the default file
  shell: rm -rf /etc/kubernetes/*

- name: config the etcd file
  template: src=etcd.conf dest=/etc/etcd/etcd.conf

- name: template the k8s file
  template: src={{ item  }} dest={{ dest_path  }}
  with_items:
    - apiserver
    - controller-manager
    - proxy
    - config 
    - kubelet
    - scheduler
  notify: start the kubernetes master
